name: Build and Deploy Frontend to Backend Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Install dependencies and build frontend
        run: |
          npm install
          npm run build

          mkdir -p static/js static/css
          
          JS_FILE=$(find dist/assets -name "*.js" | head -n 1)
          CSS_FILE=$(find dist/assets -name "*.css" | head -n 1)

          if [ -f "$JS_FILE" ]; then
            mv "$JS_FILE" static/js/main.js
          else
            echo "No JS file found"
          fi

          if [ -f "$CSS_FILE" ]; then
            mv "$CSS_FILE" static/css/main.css
          else
            echo "No CSS file found"
          fi
          
      - name: Clone backend repository
        run: |
          echo "Attempting clone from: https://alvin-wong:***@github.com/alvin-wong/VisionMD_Backend_Fork.git"
          git clone https://alvin-wong:${{ secrets.VISIONMD_BACKEND_DEPLOY_TOKEN }}@github.com/alvin-wong/VisionMD_Backend_Fork.git backend-temp

      - name: Update backend
        run: |
          cd backend-temp
          git checkout main-static
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          rm -rf static
          cp -r ../static/ ./
          git add .
          git commit -m "Automated: Update frontend build" || echo "No changes to commit"
          git remote set-url origin https://alvin-wong:${{ secrets.VISIONMD_BACKEND_DEPLOY_TOKEN }}@github.com/alvin-wong/VisionMD_Backend_Fork.git
          git push
