name: Create and Push Test File to Backend Repo

on:
  push:
    branches:
      - main

jobs:
  create-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Debug - Show Secret Availability
        run: |
          if [ -z "${{ secrets.VISIONMD_BACKEND_DEPLOY_TOKEN }}" ]; then
            echo "ERROR: Secret is not available!"
            exit 1
          else
            echo "Secret is available (value hidden for security)"
          fi

      - name: Clone backend repository
        run: |
          echo "Cloning backend repo..."
          git clone https://alvin-wong:${{ secrets.VISIONMD_BACKEND_DEPLOY_TOKEN }}@github.com/alvin-wong/VisionMD_Backend_Fork.git backend-temp

      - name: Create and push text file to backend
        run: |
          cd backend-temp
          git checkout main-static
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "This is a test file created by GitHub Actions." > test.txt
          git add .
          git commit -m "Automated: Add test text file" || echo "No changes to commit"
          git push origin main-static
